### ISSUE TITLE
Missing trademark in reference to Sprite™

### ISSUE THREAD

**Issue by dalucidi** [timgrady92/getadrink.py#1]
Lines 23 and 33 lack the appropriate trade marking required to properly honor Sprite™

**Current**
23: `print("Alright, let's get some McDonald's Sprite!")`
33: `print("Okay, I'll have some Sprite by my lonesome.")`

**Expected**
23: `print("Alright, let's get some McDonald's Sprite™!")`
33: `print("Okay, I'll have some Sprite™ by my lonesome.")`

**Comment by timgrady92** [comment]
This issue has been resolved. I have also added a trademark to the word "McDonald's" although I believe the technically correct solution would be the enclosed C. Thank you for keeping me out of jail cell and for providing valuable insight to this code.
